### ISSUE TITLE
Shift+Enter instead of Ctrl+Enter on tutorial

### ISSUE THREAD

**Issue by jm2242** [wayfair/tungstenjs#235]
In the [tutorial](http://wayfair.github.io/tungstenjs/tutorials.html), ctrl+enter doesn't run the code, it's shift+enter that does the trick.

**Comment by andrewrota** [comment]
Thanks @jm2242 that must have been an oversight.  I can probably update it later this week, or if you want to enter a PR that would be much appreciated!
