### ISSUE TITLE
Update TodoMVC examples to use filters and routing

### ISSUE THREAD

**Issue by andrewrota** [wayfair/tungstenjs#56]
Currently the examples don't implement filters or routing.  Add this functionality to match up with the [spec](https://github.com/tastejs/todomvc/blob/master/app-spec.md).

**Comment by MattDeeg** [comment]
Added filtering for the base Backbone example on branch [todomvc_spec](https://github.com/wayfair/tungstenjs/tree/todomvc_spec). ES6 and Ampersand still to go.

**Comment by andrewrota** [comment]
Added with #61
